meiduo_mall/meiduo_mall/apps/areas/urls.py
#!/usr/bin/python3
# -*- coding: utf-8 -*-
# @Author: Hui
# @Desc: { 省市区三级联动 url 配置模块 }
# @Date: 2021/10/05 15:36
from django.conf.urls import url
from . import views

urlpatterns = [
    url('^areas/$', views.AreasView.as_view())
]

meiduo_mall/meiduo_mall/apps/carts/urls.py
#!/usr/bin/python3
# -*- coding: utf-8 -*-
# @Author: Hui
# @Desc: { 购物车模块路由配置 }
# @Date: 2021/10/09 20:23
from django.conf.urls import url
from carts import views

urlpatterns = [
    url(r'^carts/$', views.CartsView.as_view(), name='info'),
    url(r'^carts/selection/$', views.CartsSelectAllView.as_view()),
    url(r'^carts/simple/$', views.CartsSimpleView.as_view()),
]

meiduo_mall/meiduo_mall/apps/goods/urls.py
#!/usr/bin/python3
# -*- coding: utf-8 -*-
# @Author: Hui
# @Desc: { 商品模块的url配置 }
# @Date: 2021/10/08 15:55
from django.conf.urls import url
from goods import views

urlpatterns = [
    url(r'^list/(?P<category_id>\d+)/(?P<page_num>\d+)/$', views.ListView.as_view(), name='list'),
    url(r'^hot/(?P<category_id>\d+)/$', views.HotGoodsView.as_view(), name='hot'),
    url(r'^detail/(?P<sku_id>\d+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^detail/visit/(?P<category_id>\d+)/$', views.DetailVisitView.as_view()),
]

meiduo_mall/meiduo_mall/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # 用户模块路由
    url(r'^', include(('users.urls', 'users'), namespace='users')),

    # 商城首页广告内容模块路由
    url(r'^', include(('contents.urls', 'contents'), namespace='contents')),

    # 验证码校验模块路由
    url(r'^', include(('verifications.urls', 'verifications'), namespace='verifications')),

    # oauth 登录认证模块
    url(r'^', include(('oauth.urls', 'oauth'), namespace='oauth')),

    # 省市区三级联动模块
    url(r'^', include(('areas.urls', 'areas'), namespace='areas')),

    # 商品模块路由
    url(r'^', include(('goods.urls', 'goods'), namespace='goods')),

    # 全文检索路由
    url(r'^search/', include('haystack.urls')),

    # 购物车模块路由
    url(r'^', include(('carts.urls', 'carts'), namespace='carts')),

    # 订单模块路由
    url(r'^', include(('orders.urls', 'orders'), namespace='orders')),

    # 阿里支付模块路由
    url(r'^', include(('payment.urls', 'payment'), namespace='payment')),

    # 美多后台管理模块路由
    url(r'^meiduo_admin/', include('meiduo_admin.urls')),
]

meiduo_mall/meiduo_mall/apps/carts/models.py
from django.db import models

# Create your models here.

meiduo_mall/meiduo_mall/apps/goods/models.py
from django.db import models
from meiduo_mall.utils.models import BaseModel


class GoodsCategory(BaseModel):
    """商品类别"""
    name = models.CharField(max_length=10, verbose_name='名称')
    parent = models.ForeignKey('self', related_name='subs', null=True, blank=True, on_delete=models.CASCADE,
                               verbose_name='父类别')

    class Meta:
        db_table = 'meiduo_goods_category'
        verbose_name = '商品类别'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsChannelGroup(BaseModel):
    """商品频道组"""
    name = models.CharField(max_length=20, verbose_name='频道组名')

    class Meta:
        db_table = 'meiduo_channel_group'
        verbose_name = '商品频道组'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class GoodsChannel(BaseModel):
    """商品频道"""
    group = models.ForeignKey(GoodsChannelGroup, verbose_name='频道组名', on_delete=models.CASCADE)
    category = models.ForeignKey(GoodsCategory, on_delete=models.CASCADE, verbose_name='顶级商品类别')
    url = models.CharField(max_length=50, verbose_name='频道页面链接')
    sequence = models.IntegerField(verbose_name='组内顺序')

    class Meta:
        db_table = 'meiduo_goods_channel'
        verbose_name = '商品频道'
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.category.name


class Brand(BaseModel):
    """品牌"""
    name = models.CharField(max_length=20, verbose_name='名称')
    logo = models.ImageField(verbose_name='Logo图片')
    first_letter = models.CharField(max_length=1, verbose_name='品牌首字母')

    class Meta:
        db_table = 'meiduo_brand'
        verbose_name = '品牌'
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.name


class SPU(BaseModel):
    """商品SPU"""
    name = models.CharField(max_length=50, verbose_name='名称')
    brand = models.ForeignKey(Brand, on_delete=models.PROTECT, verbose_name='品牌')
    category1 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat1_spu', verbose_name='一级类别')
    category2 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat2_spu', verbose_name='二级类别')
    category3 = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, related_name='cat3_spu', verbose_name='三级类别')
    sales = models.IntegerField(default=0, verbose_name='销量')
    comments = models.IntegerField(default=0, verbose_name='评价数')
    desc_detail = models.TextField(default='', verbose_name='详细介绍')
    desc_pack = models.TextField(default='', verbose_name='包装信息')
    desc_service = models.TextField(default='', verbose_name='售后服务')

    class Meta:
        db_table = 'meiduo_spu'
        verbose_name = '商品SPU'
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.name


class SKU(BaseModel):
    """商品SKU"""
    name = models.CharField(max_length=50, verbose_name='名称')
    caption = models.CharField(max_length=100, verbose_name='副标题')
    spu = models.ForeignKey(SPU, on_delete=models.CASCADE, verbose_name='商品')
    category = models.ForeignKey(GoodsCategory, on_delete=models.PROTECT, verbose_name='从属类别')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='单价')
    cost_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='进价')
    market_price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='市场价')
    stock = models.IntegerField(default=0, verbose_name='库存')
    sales = models.IntegerField(default=0, verbose_name='销量')
    comments = models.IntegerField(default=0, verbose_name='评价数')
    is_launched = models.BooleanField(default=True, verbose_name='是否上架销售')
    default_image = models.ImageField(max_length=200, default='', null=True, blank=True, verbose_name='默认图片')

    class Meta:
        db_table = 'meiduo_sku'
        verbose_name = '商品SKU'
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return '%s: %s' % (self.id, self.name)


class SKUImage(BaseModel):
    """SKU图片"""
    sku = models.ForeignKey(SKU, on_delete=models.CASCADE, verbose_name='sku')
    image = models.ImageField(verbose_name='图片')

    class Meta:
        db_table = 'meiduo_sku_image'
        verbose_name = 'SKU图片'
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return '%s %s' % (self.sku.name, self.id)


class SPUSpecification(BaseModel):
    """商品SPU规格"""
    spu = models.ForeignKey(SPU, on_delete=models.CASCADE, related_name='specs', verbose_name='商品SPU')
    name = models.CharField(max_length=20, verbose_name='规格名称')

    class Meta:
        db_table = 'meiduo_spu_specification'
        verbose_name = '商品SPU规格'
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return '%s: %s' % (self.spu.name, self.name)

    def __repr__(self):
        return self.__str__()


class SpecificationOption(BaseModel):
    """规格选项"""
    spec = models.ForeignKey(SPUSpecification, related_name='options', on_delete=models.CASCADE, verbose_name='规格')
    value = models.CharField(max_length=20, verbose_name='选项值')

    class Meta:
        db_table = 'meiduo_specification_option'
        verbose_name = '规格选项'
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __repr__(self):
        return self.__str__()

    def __str__(self):
        return '%s - %s' % (self.spec, self.value)


class SKUSpecification(BaseModel):
    """SKU具体规格"""
    sku = models.ForeignKey(SKU, related_name='specs', on_delete=models.CASCADE, verbose_name='sku')
    spec = models.ForeignKey(SPUSpecification, on_delete=models.PROTECT, verbose_name='规格名称')
    option = models.ForeignKey(SpecificationOption, on_delete=models.PROTECT, verbose_name='规格值')

    class Meta:
        db_table = 'meiduo_sku_specification'
        verbose_name = 'SKU规格'
        verbose_name_plural = verbose_name

    def __repr__(self):
        return self.__str__()

    def __str__(self):
        return '%s: %s - %s' % (self.sku, self.spec.name, self.option.value)


class GoodsVisitCount(BaseModel):
    """统计分类商品访问量模型类"""
    category = models.ForeignKey(GoodsCategory, on_delete=models.CASCADE, verbose_name='商品分类')
    count = models.IntegerField(verbose_name='访问量', default=0)
    date = models.DateField(auto_now_add=True, verbose_name='统计日期')

    class Meta:
        db_table = 'meiduo_goods_visit'
        verbose_name = '统计分类商品访问量'
        verbose_name_plural = verbose_name

meiduo_mall/meiduo_mall/apps/meiduo_admin/models.py
from django.db import models

# Create your models here.

meiduo_mall/meiduo_mall/apps/verifications/models.py
from django.db import models

# Create your models here.

meiduo_mall/meiduo_mall/apps/areas/views.py
from django.views import View
from django.core.cache import cache
from django.http import JsonResponse

from areas.models import Area
from meiduo_mall.utils.result import R
from meiduo_mall.utils.constants import RedisKey


# /areas/
class AreasView(View):
    """省市区数据"""

    def get(self, request):
        """提供省市区数据"""
        area_id = request.GET.get('area_id')

        if not area_id:
            # 读取省份缓存数据
            provinces_key = RedisKey.PROVINCES_KEY
            province_list = cache.get(provinces_key)

            if not province_list:
                # 查询省份数据
                province_model_list = Area.objects.filter(parent__isnull=True)
                # 序列化省级数据
                province_list = []
                for province_model in province_model_list:
                    province_list.append({'id': province_model.id, 'name': province_model.name})

                # 缓存省份字典列表数据:默认存储到别名为"default"的配置中
                cache.set(provinces_key, province_list, 3600)

            # 响应省份数据
            context = R.ok().data()
            context['province_list'] = province_list

            return JsonResponse(context)
        else:

            # 读取市或区缓存数据
            sub_area_key = RedisKey.SUB_AREA_KEY.format(area_id=area_id)
            sub_data = cache.get(sub_area_key)

            if not sub_data:

                # 提供市或区数据
                parent_model = Area.objects.get(id=area_id)  # 查询市或区的父级
                sub_model_list = parent_model.subs.all()

                # 序列化市或区数据
                sub_list = []
                for sub_model in sub_model_list:
                    sub_list.append({'id': sub_model.id, 'name': sub_model.name})

                sub_data = {
                    'id': parent_model.id,  # 父级pk
                    'name': parent_model.name,  # 父级name
                    'subs': sub_list  # 父级的子集
                }

                # 储存市或区缓存数据
                cache.set(sub_area_key, sub_data, 3600)

            # 响应市或区数据
            context = R.ok().data()
            context['sub_data'] = sub_data
            return JsonResponse(context)

meiduo_mall/meiduo_mall/apps/contents/views.py
from django.views import View
from django.shortcuts import render
from contents.utils import get_categories
from contents.models import ContentCategory

from meiduo_mall.utils.constants import HtmlTemplate


# /
class IndexView(View):
    """商城首页类视图"""

    def get(self, request):
        # 查询商品频道和分类
        categories = get_categories()

        # 广告数据
        contents = {}
        content_categories = ContentCategory.objects.all()
        for cat in content_categories:
            contents[cat.key] = cat.content_set.filter(status=True).order_by('sequence')

        # 渲染模板的上下文
        context = {
            'categories': categories,
            'contents': contents,
        }
        return render(request, HtmlTemplate.INDEX_HTML, context)

meiduo_mall/meiduo_mall/apps/goods/views.py
from datetime import datetime

from django import http
from django.views import View
from django.utils import timezone
from django.shortcuts import render
from django.core.paginator import Paginator
from goods import models
from goods import constants
from contents.utils import get_categories
from goods.utils import get_breadcrumb

from meiduo_mall.utils.result import R
from meiduo_mall.utils.constants import HtmlTemplate


# /list/(?P<category_id>\d+)/(?P<page_num>\d+)/
class ListView(View):
    """商品列表页"""

    def get(self, request, category_id, page_num):
        """提供商品列表页"""
        # 判断category_id是否正确
        try:
            category = models.GoodsCategory.objects.get(id=category_id)
        except models.GoodsCategory.DoesNotExist:
            return http.HttpResponseNotFound('GoodsCategory does not exist')
        # 接收sort参数：如果用户不传，就是默认的排序规则
        sort = request.GET.get('sort', 'default')

        # 查询商品频道分类
        categories = get_categories()

        # 查询面包屑导航
        breadcrumb = get_breadcrumb(category)

        # 按照排序规则查询该分类商品SKU信息
        if sort == 'price':
            # 按照价格由低到高
            sort_field = 'price'
        elif sort == 'hot':
            # 按照销量由高到低
            sort_field = '-sales'
        else:
            # 'price'和'sales'以外的所有排序方式都归为'default'
            sort = 'default'
            sort_field = 'create_time'
        skus = models.SKU.objects.filter(category=category, is_launched=True).order_by(sort_field)

        # 创建分页器：每页N条记录
        paginator = Paginator(skus, constants.GOODS_LIST_LIMIT)

        # 获取每页商品数据
        page_skus = paginator.page(page_num)

        # 获取列表页总页数
        total_page = paginator.num_pages

        # 渲染页面
        context = {
            'categories': categories,  # 频道分类
            'breadcrumb': breadcrumb,  # 面包屑导航
            'sort': sort,  # 排序字段
            'category': category,  # 第三级分类
            'page_skus': page_skus,  # 分页后数据
            'total_page': total_page,  # 总页数
            'page_num': page_num,  # 当前页码
        }
        return render(request, HtmlTemplate.GOODS_LIST_HTML, context)


# /hot/(?P<category_id>\d+)/
class HotGoodsView(View):
    """商品热销排行"""

    def get(self, request, category_id):
        """提供商品热销排行JSON数据"""
        # 根据销量倒序
        skus = models.SKU.objects.filter(category_id=category_id, is_launched=True).order_by('-sales')[:2]

        # 序列化
        hot_skus = []
        for sku in skus:
            hot_skus.append({
                'id': sku.id,
                'default_image_url': sku.default_image.url,
                'name': sku.name,
                'price': sku.price
            })

        context = R.ok().data()
        context['hot_skus'] = hot_skus
        return http.JsonResponse(context)


# /detail/(?P<sku_id>\d+)/
class DetailView(View):
    """商品详情页"""

    def get(self, request, sku_id):
        """提供商品详情页"""
        # 获取当前sku的信息
        try:
            sku = models.SKU.objects.get(id=sku_id)
        except models.SKU.DoesNotExist:
            return render(request, HtmlTemplate.ERRORS_404_HTML)

        # 查询商品频道分类
        categories = get_categories()
        # 查询面包屑导航
        breadcrumb = get_breadcrumb(sku.category)

        # 构建当前商品的规格键
        sku_specs = sku.specs.order_by('spec_id')
        sku_key = []
        for spec in sku_specs:
            sku_key.append(spec.option.id)

        # 获取当前商品的所有SKU
        skus = sku.spu.sku_set.all()
        # 构建不同规格参数（选项）的sku字典
        spec_sku_map = {}
        for s in skus:
            # 获取sku的规格参数
            s_specs = s.specs.order_by('spec_id')

            # 用于形成规格参数-sku字典的键
            key = []
            for spec in s_specs:
                key.append(spec.option.id)

            # 向规格参数-sku字典添加记录
            spec_sku_map[tuple(key)] = s.id

        # 获取当前商品的规格信息
        goods_specs = sku.spu.specs.order_by('id')

        # 若当前sku的规格信息不完整，则不再继续
        if len(sku_key) < len(goods_specs):
            return None

        for index, spec in enumerate(goods_specs):
            # 复制当前sku的规格键
            key = sku_key[:]
            # 该规格的选项
            spec_options = spec.options.all()
            for option in spec_options:
                # 在规格参数sku字典中查找符合当前规格的sku
                key[index] = option.id
                option.sku_id = spec_sku_map.get(tuple(key))
            spec.spec_options = spec_options

        # 渲染页面
        context = {
            'categories': categories,
            'breadcrumb': breadcrumb,
            'sku': sku,
            'specs': goods_specs,
        }
        return render(request, HtmlTemplate.GOODS_DETAIL_HTML, context)


# /detail/visit/(?P<category_id>\d+)/
class DetailVisitView(View):
    """详情页分类商品访问量"""

    def post(self, request, category_id):
        """记录分类商品访问量"""
        try:
            category = models.GoodsCategory.objects.get(id=category_id)
        except models.GoodsCategory.DoesNotExist:
            return http.HttpResponseForbidden('缺少必传参数')

        # 获取今天的日期
        t = timezone.localtime()
        today_str = '%d-%02d-%02d' % (t.year, t.month, t.day)
        today_date = datetime.strptime(today_str, '%Y-%m-%d')
        try:
            # 查询今天该类别的商品的访问量
            counts_data = category.goodsvisitcount_set.get(date=today_date)
        except models.GoodsVisitCount.DoesNotExist:
            # 如果该类别的商品在今天没有过访问记录，就新建一个访问记录
            counts_data = models.GoodsVisitCount()

        counts_data.category = category
        counts_data.count += 1
        counts_data.save()

        context = R.ok().data()
        return http.JsonResponse(context)

meiduo_mall/meiduo_mall/templates/users/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>多多商城-登录</title>
    <link rel="stylesheet" type="text/css" href="{{ static('css/reset.css') }}">
	<link rel="stylesheet" type="text/css" href="{{ static('css/main.css') }}">
	<script type="text/javascript" src="{{ static('js/vue-2.5.16.js') }}"></script>
    <script type="text/javascript" src="{{ static('js/axios-0.18.0.min.js') }}"></script>
</head>
<body>
	<div class="login_top clearfix">
		<a href="{{ url("contents:index") }}" class="login_logo"><img src="{{ static('images/logo02.png') }}"></a>
	</div>
	<div class="login_form_bg" id="app">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">商品美 · 种类多 · 欢迎光临</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<a href="javascript:;" class="cur">账户登录</a>
				</div>
				<div class="form_con">
					<div class="form_input cur">
						<form method="post" class="login-form" @submit="on_submit" v-cloak>
                            {{ csrf_input }}
							<input type="text" v-model="username" @blur="check_username" name="username" class="name_input" placeholder="请输入用户名或手机号">
							<div v-show="error_username" class="user_error">请输入正确的用户名或手机号</div>
							<input type="password" v-model="password" @blur="check_password" name="password" class="pass_input" placeholder="请输入密码">
							<div v-show="error_password" class="pwd_error">密码最少8位，最长20位</div>

                            {% if account_errmsg %}
                                <div class="pwd_error">{{ account_errmsg }}</div>
                            {% endif %}

                            <div class="more_input clearfix">
								<input type="checkbox" v-model="remembered" name="remembered">
								<label>记住登录</label>
							</div>
							<input type="submit" value="登 录" class="input_submit">
						</form>
					</div>
				</div>
				<div class="third_party">
					<a @click="qq_login" class="qq_login">QQ</a>
{#                    <a @click="gitee_login" class="qq_login">Gitee</a>#}
                    <a @click="gitee_login" class="qq_login">Gitee</a>
					<a href="{{ url('users:register') }}" class="register_btn">立即注册</a>
				</div>
			</div>
		</div>
	</div>
	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京多多商业股份有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
    <script type="text/javascript" src="{{ static('js/common.js') }}"></script>
	<script type="text/javascript" src="{{ static('js/login.js') }}"></script>
</body>
</html>

meiduo_mall/meiduo_mall/templates/users/user_center_order.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>多多商城-我的订单</title>
    <link rel="stylesheet" type="text/css" href="{{ static('css/jquery.pagination.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ static('css/reset.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ static('css/main.css') }}">
    <script type="text/javascript" src="{{ static('js/jquery-1.12.4.min.js') }}"></script>
    <script type="text/javascript" src="{{ static('js/vue-2.5.16.js') }}"></script>
    <script type="text/javascript" src="{{ static('js/axios-0.18.0.min.js') }}"></script>
</head>
<body>
<div id="app">
    <div class="header_con">
        <div class="header" v-cloak>
            <div class="welcome fl">欢迎来到多多商城!</div>
            <div class="fr">
                <div v-if="username" class="login_btn fl">
                    欢迎您：<em>[[ username ]]</em>
                    <span>|</span>
                    <a href="{{ url('users:logout') }}">退出</a>
                </div>
                <div v-else class="login_btn fl">
                    <a href="{{ url('users:login') }}">登录</a>
                    <span>|</span>
                    <a href="{{ url('users:register') }}">注册</a>
                </div>
                <div class="user_link fl">
                    <span>|</span>
                    <a href="{{ url('users:info') }}">用户中心</a>
                    <span>|</span>
                    <a href="{{ url('carts:info') }}">我的购物车</a>
                    <span>|</span>
                    <a href="{{ url('orders:info', args=(1, )) }}">我的订单</a>
                </div>
            </div>
        </div>
    </div>
    <div class="search_bar clearfix">
        <a href="{{ url('contents:index') }}" class="logo fl"><img src="{{ static('images/logo.png') }}"></a>
        <div class="search_wrap fl">
            <form method="get" action="/search/" class="search_con">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
            <ul class="search_suggest fl">
                <li><a href="#">索尼微单</a></li>
                <li><a href="#">优惠15元</a></li>
                <li><a href="#">美妆个护</a></li>
                <li><a href="#">买2免1</a></li>
            </ul>
        </div>
    </div>
    <div class="main_con clearfix">
        <div class="left_menu_con clearfix">
            <h3>用户中心</h3>
            <ul>
                <li><a href="{{ url('users:info') }}">· 个人信息</a></li>
                <li><a href="{{ url('users:address') }}">· 收货地址</a></li>
                <li><a href="{{ url('orders:info', args=(1, )) }}" class="active">· 我的订单</a></li>
                <li><a href="{{ url('users:password') }}">· 修改密码</a></li>
            </ul>
        </div>

        <div class="right_content clearfix">
            <h3 class="common_title2">全部订单</h3>
            {% for order in page_orders %}
                <ul class="order_list_th w978 clearfix">
                    <li class="col01">{{ order.create_time.strftime('%Y-%m-%d %H:%M:%S') }}</li>
                    <li class="col02">订单号：{{ order.order_id }}</li>
                </ul>
                <table class="order_list_table w980">
                    <tbody>
                    <tr>
                        <td width="56%">
                            {% for sku in order.sku_list %}
                                <ul class="order_goods_list clearfix">
                                    <li class="col01"><img src="{{ sku.default_image.url }}"></li>
                                    <li class="col02"><span>{{ sku.name }}</span><em>{{ sku.price }}元</em></li>
                                    <li class="col03">{{ sku.count }}</li>
                                    <li class="col04">{{ sku.amount }}元</li>
                                </ul>
                            {% endfor %}
                        </td>
                        <td width="15%">{{ order.total_amount }}元<br>含运费：{{ order.freight }}元</td>
                        <td width="15%">{{ order.pay_method_name }}</td>
                        <td width="15%">
                            <a @click="oper_btn_click('{{ order.order_id }}', {{ order.status }})"
                               class="oper_btn">{{ order.status_name }}</a>
                        </td>
                    </tr>
                    </tbody>
                </table>
            {% endfor %}
            <div class="pagenation">
                <div id="pagination" class="page"></div>
            </div>
        </div>
    </div>
    <div class="footer">
        <div class="foot_link">
            <a href="#">关于我们</a>
            <span>|</span>
            <a href="#">联系我们</a>
            <span>|</span>
            <a href="#">招聘人才</a>
            <span>|</span>
            <a href="#">友情链接</a>
        </div>
        <p>CopyRight © 2016 北京多多商业股份有限公司 All Rights Reserved</p>
        <p>电话：010-****888 京ICP备*******8号</p>
    </div>
</div>
<script type="text/javascript" src="{{ static('js/common.js') }}"></script>
<script type="text/javascript" src="{{ static('js/user_center_order.js') }}"></script>
<script type="text/javascript" src="{{ static('js/jquery.pagination.min.js') }}"></script>
<script type="text/javascript">
    $(function () {
        $('#pagination').pagination({
            currentPage: 1,
            totalPage: 3,
            callback: function (current) {
                // location.href = '/orders/info/' + current + '/';
            }
        })
    });
</script>
</body>
</html>